config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :users do
    resources :answers
    get 'matches' => 'match_connections#index', as: 'matches'
    get 'matches/:match_id' => 'match_connections#show', as: 'match'
  end
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/match_connection.rb
# == Schema Information
#
# Table name: match_connections
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  match_id   :integer
#  score      :integer
#  interested :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class MatchConnection < ActiveRecord::Base
  belongs_to :user
  belongs_to :match, class_name: "User"

  validates_uniqueness_of :user_id, :scope => :match_id

  after_create :create_inverse, unless: :has_inverse?
  after_destroy :destroy_inverse, if: :has_inverse?

  def create_inverse
    self.class.create(inverse_match_options)
  end

  def destroy_inverse
    inverses.destroy_all
  end

  def has_inverse?
    self.class.exists?(inverse_match_options)
  end

  def inverse
    self.class.where(inverse_match_options).first
  end

  def inverse_match_options
    { match_id: user_id, user_id: match_id }
  end

end

app/controllers/match_connections_controller.rb
class MatchConnectionsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @matches = @user.good_matches
    @match_connections = MatchConnection.where(user: @user, match: @matches)
  end

  def show
    @user = User.find(params[:user_id])
    @match = User.find(params[:match_id])
    @cleanliness_compatibility = CompatibilityCalculator.get_compat_score_for_category(@user, @match, "cleanliness")
    @schedule_compatibility = CompatibilityCalculator.get_compat_score_for_category(@user, @match, "schedule")
    @habits_compatibility = CompatibilityCalculator.get_compat_score_for_category(@user, @match, "habits")
  end
end

app/helpers/match_connections_helper.rb
module MatchConnectionsHelper
end

app/views/match_connections/index.html.erb
<h2 class="text-center">See Your Matches</h2>
<div class="col-md-4 col-md-offset-4">
  <% @matches.each do |match| %>
      <div class="match-section">
        <h4>
          <%= link_to match.name, user_match_path(@user, match) %>
          <span><%= @match_connections.find { |conn| conn.match == match }.score %>%</span>
        </h4>
        <em><%= match.age %> <%= match.gender %></em>
      </div>
  <% end %>
</div>

app/views/match_connections/show.html.erb
<div class="col-md-4 col-md-offset-1">
  <h2><%= @match.name %></h2>
  <h4><em><%= @match.age %> <%= @match.gender %></em></h4>
  <div class="match-section">
    <p>You are:</p>
    <p><b><%= @cleanliness_compatibility %>%</b> compatible on cleanliness</p>
    <p><b><%= @schedule_compatibility %>%</b> compatible on schedule</p>
    <p><b><%= @habits_compatibility %>%</b> compatible on habits</p>
  </div>
  <%= link_to '← Back', user_matches_path(@user) %>
</div>